In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [3]:
data = pd.read_csv("diabetes_dataset-Copy1.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
endog = data['BMI'].head(4)
exog =  data[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction']].head(4)
print(exog)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   

   DiabetesPedigreeFunction  
0                     0.627  
1                     0.351  
2                     0.672  
3                     0.167  


In [8]:
X=exog.to_numpy()
Y= endog.to_numpy()
print(X)

[[6.00e+00 1.48e+02 7.20e+01 3.50e+01 0.00e+00 3.36e+01 6.27e-01]
 [1.00e+00 8.50e+01 6.60e+01 2.90e+01 0.00e+00 2.66e+01 3.51e-01]
 [8.00e+00 1.83e+02 6.40e+01 0.00e+00 0.00e+00 2.33e+01 6.72e-01]
 [1.00e+00 8.90e+01 6.60e+01 2.30e+01 9.40e+01 2.81e+01 1.67e-01]]


In [9]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [10]:
M = mean(X.T, axis=1)
print(M)

[  4.      126.25     67.       21.75     23.5      27.9       0.45425]


In [11]:
C= X-M
print(C)

[[  2.       21.75      5.       13.25    -23.5       5.7       0.17275]
 [ -3.      -41.25     -1.        7.25    -23.5      -1.3      -0.10325]
 [  4.       56.75     -3.      -21.75    -23.5      -4.6       0.21775]
 [ -3.      -37.25     -1.        1.25     70.5       0.2      -0.28725]]


In [12]:
V = cov(C.T)
print(V)

[[ 1.26666667e+01  1.68666667e+02  1.33333333e+00 -2.86666667e+01
  -9.40000000e+01 -1.23333333e+00  7.96000000e-01]
 [ 1.68666667e+02  2.26091667e+03  5.66666667e+00 -4.30583333e+02
  -1.16716667e+03 -3.03000000e+01  1.03579167e+01]
 [ 1.33333333e+00  5.66666667e+00  1.20000000e+01  4.10000000e+01
  -3.13333333e+01  1.44666667e+01  2.00333333e-01]
 [-2.86666667e+01 -4.30583333e+02  4.10000000e+01  2.34250000e+02
   3.91666667e+01  5.54666667e+01 -1.18491667e+00]
 [-9.40000000e+01 -1.16716667e+03 -3.13333333e+01  3.91666667e+01
   2.20900000e+03  6.26666667e+00 -9.00050000e+00]
 [-1.23333333e+00 -3.03000000e+01  1.44666667e+01  5.54666667e+01
   6.26666667e+00  1.84600000e+01  1.99333333e-02]
 [ 7.96000000e-01  1.03579167e+01  2.00333333e-01 -1.18491667e+00
  -9.00050000e+00  1.99333333e-02  5.68102500e-02]]


In [13]:
values, vectors = eig(V)
print(vectors)
print(values)

[[ 5.49102743e-02  4.24681897e-02  9.96930578e-01  3.62041155e-02
  -4.44582032e-02  3.27578168e-01 -6.28163506e-03]
 [ 7.19025610e-01  6.38819235e-01 -7.57750280e-02  2.46686113e-01
   8.50695610e-02 -1.23304830e-02 -3.96665574e-03]
 [ 6.15488124e-03 -2.67497591e-02 -9.06102239e-03  2.71550838e-01
  -8.71359865e-01 -6.39116037e-01  1.03875500e-01]
 [-1.05230369e-01 -2.74238721e-01 -1.35918089e-02  8.55558545e-01
   3.71191260e-01  2.72143393e-02 -1.23446043e-03]
 [-6.84670223e-01  7.16557729e-01  2.52675448e-03  1.28314732e-01
   2.48806822e-02 -5.57135637e-03  3.41534047e-03]
 [-9.29741309e-03 -2.69968128e-02 -1.06873113e-02  3.40059038e-01
  -3.04211017e-01  4.23223024e-01 -8.68553475e-02]
 [ 3.99559604e-03  4.52934109e-04 -3.54915785e-04  3.18173309e-03
  -2.39223920e-02 -5.51526795e-01  9.90756099e-01]]
[ 3.44871054e+03  1.14882493e+03  3.54752835e-15  1.49814674e+02
 -1.17183197e-14 -3.37199123e-16 -2.80756076e-17]


In [14]:
P = vectors.T.dot(C.T)
print(P.T)

[[ 3.04225448e+01 -6.78106734e+00  1.59561207e-15  1.70552261e+01
  -4.54909391e-15 -7.79433781e-17 -1.44328993e-15]
 [-1.44921879e+01 -4.52442365e+01  2.18740687e-15 -7.81096735e+00
   1.07400822e-16  2.31200237e-15 -5.68989300e-16]
 [ 5.94280287e+01  2.57529831e+01  1.99871130e-15 -9.85777243e+00
   1.89521095e-15  2.12989613e-15  1.38777878e-15]
 [-7.53583856e+01  2.62723207e+01 -5.55970534e-15  6.13513715e-01
  -1.19381086e-16  3.79387997e-16 -4.44089210e-16]]


In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents,columns = ['principal component 1'])

In [16]:
exog1 = sm.add_constant(principalDf[['principal component 1']])
print(exog1)

   const  principal component 1
0    1.0             -30.422545
1    1.0              14.492188
2    1.0             -59.428029
3    1.0              75.358386


In [17]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(exog1,endog)
lm.coef_

array([0.        , 0.00929741])

In [18]:
lm.intercept_

27.9

In [19]:
def RSE(y_true, y_predicted):
       
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [20]:
ypred =lm.predict(exog1)

In [21]:
re = RSE(endog,ypred)
print(re)

5.219466487447417
